fix nginx X-Forwarded-Proto
zammad/zammad pull request #2863
Opened 2019-12-16 14:22 UTC by lr1980

forward the correct X-Forwarded-Proto

fixed #2829 (and yes this is a bug)

https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/32?u=lr1980

2019-12-18 12:01 UTC, waja requested changes
@lr1980 Have you tested this config? I'm running into not starting nginx, when using `map` in the `server` context. Please put it on top of the `server` context.

2019-12-18 12:01 UTC, waja commented on contrib/nginx/zammad.conf
> +    }
The map should be used outside of the `server` context. When using the config this way I'm getting:
```
nginx: [emerg] "map" directive is not allowed here in /etc/nginx/sites-enabled/default:30
```

2019-12-18 12:48 UTC, thorsteneckel commented
Hey @lr1980 - Thanks a lot for your contribution! This will help a lot of people out there.

I just checked the [NGINX documentation of this feature](http://nginx.org/en/docs/http/ngx_http_map_module.html). It was added in 2010 and got extended over  the years. It is required to have the module [`ngx_http_map_module`](http://nginx.org/en/docs/http/ngx_http_map_module.html) activated, which is [the default behavior](https://github.com/nginx/nginx/blob/953f53921505a884f3912f2d8db5217a71c0479a/auto/options#L80). So from the maintenance point of view I'd give green lights 👍 

However, there is still a syntax issues as @waja pointed out. Would you mind resolving it @lr1980 ?

2019-12-18 13:08 UTC, lr1980 commented on contrib/nginx/zammad.conf
> +    }
you are absolutely right... it's only allowed in the http context...

2019-12-18 13:23 UTC, lr1980 commented
there is still a security problem here ... in our environment (with loadbalancer) we can ensure that proto field comes from our loadbalancer. In an environment where the client / browser connects directly, it is possible that the proto field was "manipulated" by the client. i.e. if the field is used by zammad to ensure security, it is no longer possible.

I do not know the rails code that evaluates the field and therefore cannot judge how you can ensure that safety is guaranteed in every environment. it would be possible to additionally evaluate the X-Forwarded-For field to determine whether the server / client was local (private ip) or not local in front of the nginx. which also poses problems again => an own proxy / loadbalancer could also use a public ip...

this is how i come to the conclusion ... that my suggestion is a solution for our environment, but probably not a reliable (safe) solution for all environments. depending on what exactly happens or is evaluated on the rails side...

PS: the hack to write "https" directly into the config has the same security problems ...

2019-12-18 13:45 UTC, MrGeneration commented
Thanks for your feedback, maybe @thorsteneckel can give feedback on the ruby perspective.
I'll be waiting with commiting these changes until then as I don't want to raise security issues. :)

2020-03-31 08:37 UTC, hhoechtl commented
I'm also not a Ruby guy, but that security issue is usually solved by setting `TRUSTED_PROXIES` in the application.

2020-05-20 12:49 UTC, michaldaniel commented
The pull request proposes a solution for nginix only, I believe it's also necessary to reflect the changes in apache2 configuration. Something akin to:

2021-01-08 15:34 UTC, MrGeneration commented
I'll close this PR as I took your changes / suggestions to our internal git.
While I can't use your commit (and thus commiter information is lost) I did reference both your commits and Github account in the reworked commit of mine.

I hope that's okay to you!

Thank you very much for your patience and time!
My commits will reference https://github.com/zammad/zammad/issues/2829 in case you're wondering. :-)

2021-01-08 15:34 UTC, closed without merging

2021-01-08 15:39 UTC, benbucksch commented
> I can't use your commit (and thus commiter information is lost)

For future reference: `git commit --author 'His name <him@example.com>'`

2021-01-08 15:41 UTC, MrGeneration commented
Thanks for the hint. "Can't use your commit" because my software suite I am using does not support it.

2021-01-11 09:57 UTC, thorsteneckel commented
Hey there! So long story short is that we can't take this PR over to the core. As @lr1980 [mentioned earlier](https://github.com/zammad/zammad/pull/2863#issuecomment-567029245) it exposes a security issue for non load-balancer setups.

I'll address the further processing in issue #2829.

PS @MrGeneration : Please refer to our internal wiki documentation on how to keep the original PR commit author.