Translation introduction text shows wrong keyboard shortcut
zammad/zammad pull request #3990
Opened 2022-02-28 15:05 UTC by rotimiazeez

## Issue Description
When opening the translation menu within the admin settings, the introduction text will show the keyboard shortcut for inline translation for macOS, no matter if you're on macOS or not.

[Issue Link]()https://github.com/zammad/zammad/issues/2885

## Proposed Solution
Create a variable for the enable/disable inline translation inside the view template in translation.coffee file, then call it inside the app/assets/javascript/app/view/translation/index.jst.eco file to replace the hardcoded inline translation shortcut.

## Screenshots  

### Before

![zammad](https://user-images.githubusercontent.com/44624138/155853491-d1c199d4-278c-4efb-9923-be83739da4ef.png)
![zammad3](https://user-images.githubusercontent.com/44624138/155853495-3d2921a9-e0f8-4aab-9179-3431d6557b7d.png)

### After
- MacOS
![screenshot (11)](https://user-images.githubusercontent.com/44624138/155853509-5c8997e5-2554-4f73-b147-1c98695c723b.png)

- Windows / Linux
![screenshot (12)](https://user-images.githubusercontent.com/44624138/155853522-c2e0e075-27bd-4f6f-b362-27f73274cae1.png)

## Code Changes
- Modify translation.coffee file.
- Remove hardcoded shortcut form pp/assets/javascript/app/view/translation/index.jst.eco file.

2022-03-10 07:24 UTC, dominikklein requested changes
Hi @rotimiazeez 

thanks for the detailed PR.

I added a comment which needs to be changed and is it possible for you to extend the existing test case for this area?

Best regards,
Dominik

2022-03-10 07:24 UTC, dominikklein commented on app/assets/javascripts/app/views/translation/index.jst.eco
> +    <p><%- @T('To make translations easier you can enable and disable the inline translation feature by pressing ') %><%= @inlineTranslationKey%></p>
Here the placeholder `%s` was removed from the translatable string. This needs to be corrected to have the possibility to translate the sentence without this hardcoded output at the end.

2022-03-10 22:53 UTC, rotimiazeez commented
## Hi @dominikklein 👋🏽,

I appreciate the review 💯, I'll see to the requested change and get in touch as soon as possible 🙏🏽.

Best regards,
Azeez.

2022-03-16 06:31 UTC, rotimiazeez commented
### Hi @dominikklein 👋🏽,
> I made the changes as requested and tried to extend the test case for the inline translation page 💪🏽.
Kindly review and give your feedback on it 🙏🏽 
Best regard.

2022-03-22 14:58 UTC, closed without merging

2022-03-22 15:00 UTC, dominikklein commented
Hi @rotimiazeez

thanks for your contribution, this PR is now merged with the above commit.
I needed only to align some things for the test (feel free to take a look).

Best regards,
Dominik

2022-03-22 15:39 UTC, rotimiazeez commented
@dominikklein 👋🏽,

It's a pleasure contributing to the codebase 😃.

No problem regarding the lost author 💪🏽.

Best regards,
Azeez.